# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - dir: ./cmd/anemometer
    env:
      - CGO_ENABLED=0
    flags:
      - -v
    ldflags:
      - -X github.com/simplifi/anemometer/pkg/anemometer/version.Version={{.Version}}
    targets:
      - go_first_class

archives:
  - formats: ['tar.gz']
    format_overrides:
      - goos: windows
        formats: ['zip']

dockers:
  - image_templates:
      - "ghcr.io/simplifi/anemometer:{{ .Tag }}"
      - "ghcr.io/simplifi/anemometer:latest"

checksum:
  name_template: "checksums.txt"

changelog:
  disable: true
